name: Release-pipeline
# ENV section is mandatory
env:
  app_name: 'some_name' # name of the app. A folder with this name will be createrd in the app of apps folder
  container_name: $app_name # normally same ass app_name but change it if you will deploy ui + api for example.
  build_context: './path/to/dockerfile' # relative to root of build repo
  team: 'your team' # d, e, got, itot etc. 
##########################################
  acr_repo: 'skfse11gacr.azurecr.io' # use your acr repo
  environment: 'dev'
  manifest_path: ./$team/$app_name/$environment
  containerTag: skfse11g-$team-$container_name
# only run workflow when a new version is released. The docker image will get
# the version tag and the 'latest' tag
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout build repo
        uses: actions/checkout@v3

      - name: login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.acr_repo}}
          username: ${{ secrets.SKFSE11GACR_USER }}
          password: ${{ secrets.SKFSE11GACR_PASSWORD }}

      - name: Get the version
        id: vars
        run: echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build the tagged Docker image
        uses: docker/build-push-action@v3
        with:
         context: .
         file: ${{env.build_context}}/Dockerfile
         push: true
         tags: ${{env.acr_repo}}/${{contaierTag}}:${{steps.vars.outputs.tag}}
            
      - uses: actions/checkout@v3
        name: Checkout Manifests 
        with:
          repository: ${{github.repository_owner}}/${{secrets.MANIFESTS}}
          token: ${{secrets.PAT}}
      - name: update manifest
        run: |
          mkdir -p ${{env.manifest_path}} 
          echo "{tag: '${{steps.vars.outputs.tag}}', containerName: '${{env.containerTag}}', repository: '${{env.acr_repo}}'}" > ${{env.manifest_path}}/${{env.app_name}}.libsonnet
        working-directory: .
      - name: Commit changes
        run: |
          git config --global user.name 'skfse11g'
          git add .
          git commit -am "Updates to ${{steps.vars.outputs.tag}}"
          git push
